---
- name: Create User
  gather_facts: no
  hosts: all
  tasks:
    - name: Add the user and Password , Assign to Group 
      user:
        name: '{{ var_user }}'
        group: '{{ var_group }}'
        password: '{{ var_password }}'
