---
- name: Copying file konven f1 to dir3
  copy:
    src: "{{ dir1 }}/{{ f1 }}"
    dest: "{{ dir3 }}"
    remote_src: yes

- name: Copying file syariah f1 to dir4
  copy:
    src: "{{ dir2 }}/{{ f1 }}"
    dest: "{{ dir4 }}"
    remote_src: yes

- name: log for copied files
  lineinfile:
    path: "{{ log1 }}"
    line: "{{ date }} file {{ f1 }} for konven and syariah found and copied locally"

- name: merge files
  shell: "cat {{ dir3 }}/{{ f1 }} {{ dir4 }}/{{ f1 }} >> {{ f11 }}"
  ignore_errors: yes

- name: log for merged files
  lineinfile:
    path: "{{ log1 }}"
    line: "{{ date }} file {{ f1 }} for konven and syariah has been merged"

- name: Check if f11 is exists
  stat:
    path: "{{ f11 }}"
  register: f11_status

- name: log if f11 file not exist
  lineinfile:
    path: "{{ log1 }}"
    line: "{{ date }} backup locally failed"
  when: f11_status.stat.exists == False

- name: Fail when f11 is missing
  fail:
    msg: "File f11 is missing"
  when: f11_status.stat.exists == False

- name: Copying f11 to dir0
  copy:
    src: "{{ f11 }}"
    dest: "{{ dir0 }}"
    remote_src: yes
  notify: sending_status

- name: Cleanup konven f1 from dir3
  file:
    path: "{{ dir3 }}/{{ f1 }}"
    state: absent
    
- name: Cleanup syariah f1 from dir3
  file:
    path: "{{ dir4 }}/{{ f1 }}"
    state: absent
    
