---
- name: check availability of FTP server
  wait_for:
    port: 21
    host: "{{ h0 }}"
    search_regex: vsFTPd
    delay: 1
    timeout: 5
  register: result
  ignore_errors: yes

- name: log if FTP server not available
  lineinfile:
    path: "{{ log1 }}"
    line: "FTP {{ h0 }} UNREACHABLE on {{ date }}"
  when: result.failed == True
  
- name: failed when FTP server is not available
  fail:
    msg: "FTP server is not available"
  when: result.failed == True

- name: log if FTP server is available
  lineinfile:
    path: "{{ log1 }}"
    line: "FTP {{ h0 }} REACHABLE on {{ date }}"

- name: upload file
  shell: |
    lftp {{ h0 }}<<EOF
    cd testing
    put {{ dir5 }}/{{ f1 }}
    lcd {{ dir6 }}
    get {{ f1 }}
    bye
    EOF
  register: ftpresult

- debug:
    var: ftpresult
    
- name: sending tasks
  debug:
    msg: "File is succesfully sent"

