---
- name: Perform file management playbook
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes
  
  tasks:
  - debug:
      msg: "Starting Logging for {{ target_group }}"

  - name: set log1 var fact
    set_fact:
      log1: "/ftp_3/testing/log/{{ date }}.testing.log"
  
  - name: set f1 var fact
    set_fact:
      f1: "123456_testing_{{ date }}.txt"

  - name: set f11 var fact
    set_fact:
      f11: "/ftp_3/testing/kirim/123456_testing_{{ date }}.txt"

  - debug:
      msg: "Test var {{ log1 }} and {{ f1 }} and {{ f11 }}"

  - name: Create initial log file
    file: 
      path: "{{ log1 }}"
      state: touch
    
  - name: create log into log file
    lineinfile:
      path: "{{ log1 }}"
      line: log created at {{ date }} for testing

  - name: Check if dir1 is exists
    stat:
      path: "{{ dir1 }}"
    register: dir1_status

  - name: Check if dir2 is exists
    stat:
      path: "{{ dir2 }}"
    register: dir2_status
  
  - name: Check f1 on dir1 is exists
    stat:
      path: "{{ dir1 }}/{{ f1 }}"
    register: d1f1_status

  - name: Check f1 on dir2 is exists
    stat:
      path: "{{ dir2 }}/{{ f1 }}"
    register: d2f1_status

  - name: Fail when both directory is missing
    fail:
      msg: "Both directory is missing!! Please Check NFS server"
    when: dir1_status.stat.exists == False and dir2_status.stat.exists == False

  - name: Load copy_merge role when both directory and file inside directory is available
    include_role:
      name: "copy_merge"
    when: 
      - dir1_status.stat.exists
      - dir2_status.stat.exists
      - d1f1_status.stat.exists
      - d2f1_status.stat.exists
  
  - name: Load d2f1_miss role when d2f1 is missing
    include_role:
      name: "d2f1_miss"
    when: 
      - dir1_status.stat.exists
      - dir2_status.stat.exists
      - d1f1_status.stat.exists
      - d2f1_status.stat.exists == False


  - name: Load d1f1_miss role when d2f1 is missing
    include_role:
      name: "d1f1_miss"
    when: 
      - dir1_status.stat.exists
      - dir2_status.stat.exists
      - d1f1_status.stat.exists == False
      - d2f1_status.stat.exists 
