---
- name: Perform Step 1 file check
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes
  
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  
  tasks:
  - debug:
      msg: "Starting Logging for {{ target_group }}"


  - name: Create initial log
    file: 
      path: /ftp_3/testing/log/{{ date }}.testing.log
      state: touch
    
