---
- name: Perform Step 1 file check
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes
  
    tasks:
  - debug:
      msg: "Starting Logging for {{ target_group }}"


  - name: Create initial log file
    file: 
      path: /ftp_3/testing/log/{{ date }}.testing.log
      state: touch
    
  - name: create log into log file
    lineinfile:
      path: /ftp_3/testing/log/{{ date }}.testing.log
      line: log created at {{ date }} for testing

  - name: Check if dir1 is exists
    stat:
      path: "{{ dir1 }}"
    register: dir1_status

  - name: Check if dir2 is exists
    stat:
      path: "{{ dir2 }}"
    register: dir2_status

  - name: Load roles when both directory is available
    include_role:
      name: "copy_merge"
    when: dir1_status.stat.exists and dir2_status.stat.exists

  - name: Fail when dir1 is missing
    fail:
      msg: "Directory dir1 is missing"
    when: dir1_status.stat.exists == False

  - name: Fail when dir2 is missing
    fail:
      msg: "Directory dir2 is missing"
    when: dir2_status.stat.exists == False

