---
- name: Perform file management playbook
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes
  
  tasks:
  - debug:
      msg: "Starting Logging for {{ target_group }}"

  - name: set log1 var fact
    set_fact:
      log1: "/ftp_3/testing/log/{{ date }}.testing.log"
  
  - name: set f1 var fact
    set_fact:
      f1: "123456_testing_{{ date }}.txt"

  - name: set f11 var fact
    set_fact:
      f11: "/ftp_3/testing/kirim/123456_testing_{{ date }}.txt"

  - debug:
      msg: "Test var {{ log1 }} and {{ f1 }} and {{ f11 }}"

  - name: Create initial log file
    file: 
      path: "{{ log1 }}"
      state: touch
    
  - name: create log into log file
    lineinfile:
      path: "{{ log1 }}"
      line: log created at {{ date }} for testing

  - name: Check if dir1 is exists
    stat:
      path: "{{ dir1 }}"
    register: dir1_status

  - name: Check if dir2 is exists
    stat:
      path: "{{ dir2 }}"
    register: dir2_status

  - name: Load copy_merge roles when both directory is available
    include_role:
      name: "copy_merge"
    when: dir1_status.stat.exists and dir2_status.stat.exists

  - name: Fail when both directory is missing
    fail:
      msg: "Both directory is missing!!"
    when: dir1_status.stat.exists == False and dir2_status.stat.exists == False

  - name: Load dir1 roles when dir1 is missing
    include_role:
      name: "dir1_missing"
    when: dir1_status.stat.exists == False

  - name: Load dir2 roles when dir is missing
    include_role:
      name: "dir2_missing"
    when: dir2_status.stat.exists == False

