---
- name: Create or delete db on Postgres
  hosts: "{{ target_node }}"
  become: yes
  gather_facts: yes

  tasks:
  - name: ensure the database is present/absent
    postgresql_db: >
      state={{ state }}
      db={{ dbname }}
      login_user={{ dbuser }}
      login_password={{ dbpass }}
      login_host={{ dbhost }}
      port={{ dbport }}