date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
dir0: "{{ '/backup_ftp/testing' }}"
dir1: "{{ '/core/konven/testing-konven/kirim' }}"
dir2: "{{ '/core/konven/testing-syariah/kirim' }}"
dir3: "{{ '/ftp_3/testing/temp/konven' }}"
dir4: "{{ '/ftp_3/testing/temp/syariah' }}"
dir5: "{{ '/ftp_3/testing/kirim' }}"
dir6: "{{ /ftp_3/testing/cek }}"
dir10: "{{ /core/konven/testing-konven/backup }}"
dir20: "{{ /core/konven/testing-syariah/backup }}"
h0: "{{ 'rhel8' }}"